# Generated by Django 4.2.29 on 2026-03-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_allergies',
            field=models.TextField(blank=True, default='', help_text='Перелік алергій (напр. лактоза, горіхи)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_custom_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_instructions',
            field=models.TextField(blank=True, default='', help_text='Як бот має до вас звертатися або інші побажання'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coins',
            field=models.IntegerField(default=0, help_text='Внутрішньоігрова валюта'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Чи є користувач PRO (безлімітні тікети та додаткові функції)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tickets',
            field=models.IntegerField(default=5, help_text='Тікети для доступу до AI функцій'),
        ),
    ]
