# Generated by Django 6.0.1 on 2026-02-02 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Назва продукту')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категорія')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Зображення (URL)')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Штрихкод')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Каталог Продуктів',
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Shopping List', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Списки покупок',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва магазину')),
                ('url_base', models.URLField(verbose_name='Базове URL')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Довгота')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазини',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('price_value', models.FloatField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='core.product')),
            ],
            options={
                'verbose_name': 'Історія цін',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_checked', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shoppinglist')),
            ],
            options={
                'verbose_name': 'Позиція списку',
                'verbose_name_plural': 'Позиції списку',
            },
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='items',
            field=models.ManyToManyField(through='core.ShoppingListItem', to='core.product'),
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (UAH)')),
                ('weight_gram', models.FloatField(blank=True, null=True, verbose_name='Вага (г)')),
                ('price_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна за 100г')),
                ('ingredients_text', models.TextField(blank=True, verbose_name='Склад')),
                ('quality_score', models.IntegerField(blank=True, null=True, verbose_name='Оцінка якості (1-10)')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Посилання на товар')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='core.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.store')),
            ],
            options={
                'verbose_name': 'Товарна позиція',
                'verbose_name_plural': 'Ціни в магазинах',
                'ordering': ['price'],
                'unique_together': {('store', 'product')},
            },
        ),
    ]
